project:
  type: website

website:
  title: "Geography 385: Spatial Data Analysis"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Lectures"
        menu:
          - text: "08-26 Course Overview"
            href: lectures/week01/index.qmd
          - text: "09-09 Spatial Data Analysis"
            href: lectures/week01/lecture_sda.qmd
          - text: "09-16 Area Unit Data"
            href: lectures/week04/lecture_area.qmd
          - text: "09-23 Choropleth Maps"
            href: lectures/week05/choro.qmd
          - text: "09-30 Spatial Weights"
            href: lectures/week06/spatial_weights.qmd
          - text: "10-07 Global Spatial Autocorrelation"
            href: lectures/week07/global.qmd
          - text: "10-14 Local Spatial Autocorrelation"
            href: lectures/week08/local.qmd
          - text: "10-21 Clustering and Regionalization"
            href: lectures/week09/regionalization.qmd
      - text: "Studio"
        menu:
          - text: "08-28 Studio 1: Juptyer Hub Introduction"
            href: studio/week01/index.qmd
          - text: "09-04 Studio 2: Pandas"
            href: studio/week02/index.qmd
          - text: "09-11 Studio 3: GeoPandas"
            href: studio/week03/index.qmd
          - text: "09-18 Studio 4: GeoProcessing"
            href: studio/week04/index.qmd
          - text: "09-25 Studio 5: Choropleth Mapping "
            href: studio/week05/index.qmd
          - text: "10-02 Studio 6: Peer Evaluation 1"
            href: studio/week06/peer1.qmd
          - text: "10-09 Studio 7: Global Spatial Autocorrelation"
            href: studio/week07/global.qmd
          - text: "10-16 Studio 8: Local Spatial Autocorrelation"
            href: studio/week08/local.qmd
          - text: "10-21 Clustering and Regionalization"
            href: lectures/week09/regionalization.qmd	    
      - text: "References"
        href: references.qmd
    right:
      - text: "About"
        href: about.qmd
  sidebar:
    - section: "Weeks"
      contents:
        - text: "08-26 Course Overview"
          href: lectures/week01/index.qmd
        - text: "08-28 Studio 1: Jupyter Hub"
          href: studio/week01/index.qmd
        - text: "09-04 Studio 2: Pandas"
          href: studio/week02/index.qmd
        - text: "09-09 Spatial Data Analysis"
          href: lectures/week03/index.qmd
        - text: "09-11 Studio 3: GeoPandas"
          href: studio/week03/index.qmd
        - text: "09-16 Area Unit Data"
          href: lectures/week04/lecture_area.qmd
        - text: "09-18 Studio 4: Geosnap and Geoprocessing"
          href: studio/week04/index.qmd
        - text: "09-23 Choropleth Mapping"
          href: lectures/week05/choro.qmd
        - text: "09-25 Studio 5: Choropleth Mapping "
          href: studio/week05/index.qmd
        - text: "09-30 Spatial Weights"
          href: lectures/week06/spatial_weights.qmd
        - text: "10-02 Studio 6: Peer Evaluation 1"
          href: studio/week06/peer1.qmd
        - text: "10-07 Global Spatial Autocorrelation"
          href: lectures/week07/global.qmd
        - text: "10-09 Studio 7: Global Spatial Autocorrelation"
          href: studio/week07/global.qmd
        - text: "10-14 Local Spatial Autocorrelation"
          href: lectures/week08/local.qmd
        - text: "10-16 Studio 8: Local Spatial Autocorrelation"
          href: studio/week08/local.qmd
    - section: "Resources"
      contents:
        - text: "Syllabus"
          href: syllabus.qmd

format:
  html:
    css: styles/custom.scss
    toc: true
    toc-depth: 3
    code-fold: true
    code-tools: true

bibliography: 385.bib
